#!/bin/bash

echo 'compiling...'

rm -f a.out
#g++ -lcurl -Wall -W $1 $2 $3 $4 $5 $6 $7 $8 $9
#g++ -Wall -W -g -lcurl -levent -lmysqlclient -L/opt/libevent/lib -L/usr/lib/mysql -I/opt/libevent/include -I/usr/include/mysql -I/usr/include $1 $2 $3 $4 $5 $6 $7 $8 $9
g++ -Wall -W -g -levent -lmysqlclient -L/usr/local/curl73/lib -lcurl -L/opt/libevent/lib -L/usr/lib/mysql -I/usr/local/curl73/include -I/opt/libevent/include -I/usr/include/mysql -I/usr/include $1 $2 $2 $4 $5 $6 $7 $8 $9

./a.out
